-- V2 Phase 1 (HT-B): extend the existing product catalog into the Store.
-- PRD-v2.md §2. New columns only — the existing flat member-read/write RLS
-- on `products` (20260904120010) is untouched; categories stay admin-gated
-- (Phase 0), catalog *items* stay flat, same as today.

alter table public.products
  add column category_id           text references public.product_categories (id),
  add column vendor_name           text check (vendor_name is null or char_length(vendor_name) <= 200),
  add column datasheet_path        text,                          -- storage.objects path, not a URL (signed on read)
  add column image_paths           text[] not null default '{}'::text[],
  add column price_amount          numeric(14,2) check (price_amount is null or price_amount >= 0),
  add column price_currency        text not null default 'NGN' check (price_currency in ('NGN','USD')),
  add column oem                   boolean not null default false,
  add column archived_at           timestamptz,
  add column search_count          integer not null default 0,
  add column added_to_quote_count  integer not null default 0;

-- Backfill the 6 seeded products into their matching Phase-0 category (the
-- category ids were deliberately chosen to mirror these product ids).
update public.products set category_id = case id
  when 'drone'        then 'drone-uav-systems'
  when 'rov'           then 'rov-systems'
  when 'crawler'       then 'crawler-systems'
  when 'cleaning'      then 'cleaning-equipment'
  when 'platform'      then 'inspection-platforms'
  when 'surveillance'  then 'surveillance-systems'
  else category_id
end
where category_id is null;

alter table public.products alter column category_id set not null;
create index products_category_id_idx on public.products (category_id);

-- Widen the status enum for bulk-uploaded rows ("status can be updated
-- later" — item 1a). Looked up dynamically rather than assuming the
-- autogenerated constraint name, since it was never explicitly named.
do $$
declare
  c text;
begin
  select conname into c
  from pg_constraint
  where conrelid = 'public.products'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%status%Active%';
  if c is not null then
    execute format('alter table public.products drop constraint %I', c);
  end if;
end $$;

alter table public.products
  add constraint products_status_check
  check (status in ('Active', 'Pilot', 'Planned', 'Pending Review'));
